apply:
  name: Terraform Apply (Manual with Approval)
  runs-on: ubuntu-latest
  if: github.event_name == 'workflow_dispatch' && toLower(github.event.inputs.apply) == 'yes'
  environment: production   # Manual approval required

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
